### PR TITLE
Php54 reverse proxy server handler

### PR DESCRIPTION
**Pull request by nazgu1**
Hey,
I added another handler for PHP 5.4 build-in server. I wrote it for my needs and I think it could be useful for somebody else.

It's lacking functional tests, because I have no idea how to test it (without providing php5.4 binaries

I also added Usage section to Readme and formated it Markdown.

Cheers :)

### CODE REVIEW

**Comment by eric1234** [comment]
Interesting to know php has built it's own web server. Didn't know about that. Having that available really removes part of the reason I created the rack_legacy executable. I wanted to be able to do the equivalent of "rails s" on a PHP project without having to setup, configure and maintain Apache or Nginx.

But of course there is still the use case of having a Ruby/Rails project that is using a bit of PHP. In that case you still want Rack up front for your Ruby stuff and the PHP for the legacy stuff. Have the PHP handled by this PHP server certainly would be better performance than running it through php-cgi.

My question is why can't use use the rack_reverse_proxy you borrowed from in that case and not use Rack-Legacy at all. So the setup would be:
1. Request comes in
2. If request meets certain criteria (ends in .php, is in certain directory, etc.) it proxies to the PHP Server via rack_reverse_proxy.
3. Otherwise it assumes the request can be handled by Ruby and it falls through

Seems that getting Rack-Legacy involved is really not necessary as Rack, rack_reverse_proxy and PHP Server have all the pieces you need.

I haven't taken a close look at your patch but that is my initial thoughts. A handler for PHP Server is not necessary since RackLegacy is not the proper tool in that case. Would be interested in knowing why these thoughts are wrong if they are.

**Comment by nazgu1** [comment]
Yes, you think right, but there some things that I think suit well to this project.

First, I'd like to run php server on rack server start (to use pow utility), but maybe there is another way.

Second, I can have a one gem with support older versions cgi and 5.4 http server.

Third, it will be easy to respect .htaccess php directives (as in php-cgi) that sometimes may be usefull.

I wrote it mainly for easy integrate my php project with pow.

So, that's some points to consider. I requested pull, because I think it can be useful for other people.

– David.

**Comment by eric1234** [comment]
Been meaning to get back to you on this. Although I appreciate you sending along your pull request I don't think it is right for this project currently for the following reasons:
- It doesn't really do much over what the current cgi-based version does. At most it might be a bit faster but for development I think the CGI version is fast enough. So it adds a lot of code to the project that must be maintained without a clear benefit.
- I would rather add rack-reverse-proxy as a dependency and configure it over copying/pasting into this project.
- You obviously used the CGI version as a base and modified from there. But it looks like there are some left-overs from the CGI version that I would prefer to clean-up (incorrect comments, un-used private helper methods, etc.)
- You mentioned the testing is not quite complete. I spent a lot of time getting complete testing and I want to keep that standard. We can assume the binaries are installed but we do need functional testing.

I might change my mind later if the PHP Server offers clear benefit as the other points could be address pretty quickly. But at this time I don't see any reason to address the other issues since the primary issue (no clear purpose over the CGI version) would still block it getting pulled.

Obviously sharing your version is great as others may find it useful and they can go to your branch to get it. Not enough people contribute back and I do thank you for your effort.

**Comment by eric1234** [comment]
Just wanted to send a followup on this. I ran into an issue where Mongo was taking a while to make a connection in PHP. On a standard stack (Apache, etc) this wasn't a big deal because the connection was cached between requests. But using the CGI approach on rack-legacy it was far too slow.

So I used your idea of proxying off to PHP's built-in web-server using rack-reverse-proxy. While [the patch](https://github.com/eric1234/rack-legacy/commit/14ae71bad2dfca52b365c90de042176a238d2340) didn't use any of your work directly it did use the same basic idea (rack-reverse-proxy + php -S). So just wanted send you a thanks for your approach. This new version completely replaces the CGI-based implementation for PHP.

**Comment by nazgu1** [comment]
Thanks for notifying me. It is nice to see you use my idea in your code. 

Wiadomość napisana przez Eric Anderson notifications@github.com w dniu 12 lis 2013, o godz. 20:52:

**Pull request closed without merging**
